import React from "react";
import SellCar from "@/layout/user/jual-mobil/SellCar";
import CarouselGlobal from "@/components/product-user/CarouselGlobal";
import SellBedge from "@/layout/user/jual-mobil/SellBedge";
import SellAccordion from "@/layout/user/jual-mobil/SellAccordion";

export const metadata = {
  title: "Jual Mobil | Mukrindo Motor",
  description: "Generated by Mukrindo Motor",
};

const SellCarPage = () => {
  return (
    <div className="min-h-screen">
      <CarouselGlobal
        imageUrl="/images/placeholder-banner.jpg"
        imageAlt="Jual Mobil Cepat dan Aman"
        title="Jual Mobil Cepat Laku & Aman"
        subtitle="Bebas Drama & Tipu-Tipu"
      />
      <SellCar />
      <div className="px-4 lg:px-0 space-y-8 lg:space-y-16">
        <SellBedge />
        <SellAccordion />
      </div>
    </div>
  );
};

export default SellCarPage;
