// app/beli-mobil/[slug]/page.jsx

import React from "react";
import BuyCarDetails from "@/layout/user/beli-mobil/BuyCarDetails";
import Testimoni from "@/components/product-user/Testimoni";
import NotifyMeForm from "@/components/product-user/NotifyMeForm";
import BuyCarAccordion from "@/layout/user/beli-mobil/BuyCarAccordion";

export const metadata = {
  title: "Beli Mobil | Mukrindo Motor",
  description: "Generated by Mukrindo Motor",
};

export default function DetailCarPage({ params }) {
  const { slug } = params;
  const productId = slug.substring(slug.lastIndexOf("-") + 1);

  return (
    <div className="container mx-auto">
      <div className=" lg:pt-10 border-t-2 border-gray-200 space-y-4 lg:space-y-16">
        <BuyCarDetails productId={productId} />
        <Testimoni />
        <NotifyMeForm />
        <BuyCarAccordion />
      </div>
    </div>
  );
}
