import { Poppins } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import RootLayoutClient from "./layout.client";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Mukrindo Motor",
  description: "Generated by Mukrindo Motor",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${poppins.variable} antialiased`}>
        <Suspense fallback={<div>Loading...</div>}></Suspense>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
